### ISSUE TITLE
Places to be corrected

### ISSUE THREAD

**Issue by wangzhenhui1992** [mbadry1/DeepLearning.ai-Summary#1]
I found some places which need to be corrected.

[Other regularization methods](https://github.com/mbadry1/DeepLearning.ai-Summary/tree/master/2-%20Improving%20Deep%20Neural%20Networks#other-regularization-methods)
incorrect: For example in OCR, you'll need the distort the digits.
correct   : For example in OCR, you'll need to distort the digits.

[Vanishing / Exploding gradients](https://github.com/mbadry1/DeepLearning.ai-Summary/tree/master/2-%20Improving%20Deep%20Neural%20Networks#vanishing--exploding-gradients)
incorrect:  And If W < I (Identity matrix) The weights will explode
correct   :  And If W < I (Identity matrix) The weights will vanish

Thank You

**Comment by mbadry1** [comment]
These mistakes has been updated.
Thank you so much for notifying me with such mistakes. I there are more you see, just open another issue and i will resolve them.
