### ISSUE TITLE
Difficult to understand

### ISSUE THREAD

**Issue by wangzhenhui1992** [mbadry1/DeepLearning.ai-Summary#10]
[Language model and sequence generation](https://github.com/mbadry1/DeepLearning.ai-Summary/tree/master/5-%20Sequence%20Models#language-model-and-sequence-generation)

> The job of a language model is given any sentence give a probability of that sentence. Also what is the next sentence probability given a sentence.

It is difficult to understand.
Is this meaning?

> The job of a language model is giving a probability of any given sentence .Also the probability of the next sentence.

**Comment by mbadry1** [comment]
Yes, Its so much better.
I will update it.
Thank you
