### ISSUE TITLE
maybe there are something wrong in your note

### ISSUE THREAD

**Issue by zhuzhanshi** [mbadry1/DeepLearning.ai-Summary#164]
Title： Normalizing activations in a network
the last line, the last character
if gamma = sqrt(variance + epsilon) and beta = mean then Z_tilde[i] = Z_norm[i] 
I think there should be : if gamma = sqrt(variance + epsilon) and beta = mean then Z_tilde[i] = Z[i]

**Comment by mbadry1** [comment]
Yes you are right. I'm going to fix this.
Thank you so much
