### ISSUE TITLE
Unable to be represented

### ISSUE THREAD

**Issue by wangzhenhui1992** [mbadry1/DeepLearning.ai-Summary#21]
[Properties of word embeddings](https://github.com/mbadry1/DeepLearning.ai-Summary/tree/master/5-%20Sequence%20Models#properties-of-word-embeddings)

> $$\text{CosineSimilarity(u, v)} = \frac {u . v} {||u||_2 ||v||_2} = cos(\theta)$$

It seems to have a wrong representation with markdown language and need to be fixed,right?

**Comment by mbadry1** [comment]
I've copied the same markdown from the exercise notebooks.
It works in jupyter notebook, Typora (https://typora.io/), and pandoc.
I don't know why github can't draw it!

I''ve let it in case someone has extracted the PDF using the python code that I've provided with notes

**Comment by VladKha** [comment]
This is LaTeX, which is correctly rendered in Jupyter, but GitHub currently doesn't render LaTeX at all

More info can be found [here](https://stackoverflow.com/questions/35498525/latex-rendering-in-readme-md-on-github)

@mbadry1 I think, this issue can be closed
