### ISSUE TITLE
Mistake！

### ISSUE THREAD

**Issue by wangzhenhui1992** [mbadry1/DeepLearning.ai-Summary#4]
[Train / Dev / Test sets](https://github.com/mbadry1/DeepLearning.ai-Summary/tree/master/2-%20Improving%20Deep%20Neural%20Networks#train--dev--test-sets)

> If size of the dataset is 100 to 1000000 ==> 60/20/20
> If size of the dataset is 1000000 to INF ==> 99/1/1 or 99.5/0.25/0.25

According to this lesson, it should be 98/1/1 but not  99/1/1.

**Comment by mbadry1** [comment]
Typo again.
Thanks for mentioning.
