### ISSUE TITLE
Mistake

### ISSUE THREAD

**Issue by wangzhenhui1992** [mbadry1/DeepLearning.ai-Summary#5]
Thanks for your summary.
I'm now at the forth course of deeplearning.ai.
And I found a mistake.

[Convolutional Implementation of Sliding Windows](https://github.com/mbadry1/DeepLearning.ai-Summary/tree/master/4-%20Convolutional%20Neural%20Networks#convolutional-implementation-of-sliding-windows)

> As you can see in the above image, we turned the FC layer into a Conv layer using a convolution with the width and height of the filter is the same as the **with** and height of the input.

It should be "width" instead of "with".

**Comment by mbadry1** [comment]
It has been fixed.
Thanks for helping me fixing my notes. I've added an acknowledgement for you in the homepage.
Hope you finish deeplearning.ai courses soon and do best deep learning applications.

**Comment by wangzhenhui1992** [comment]
Thank you.
Can I do Merge Request to fix instead of issue?

**Comment by mbadry1** [comment]
Yes you can
