### ISSUE TITLE
Limitation

### ISSUE THREAD

**Issue by wangzhenhui1992** [mbadry1/DeepLearning.ai-Summary#8]
[Recurrent Neural Network Model](https://github.com/mbadry1/DeepLearning.ai-Summary/tree/master/5-%20Sequence%20Models#recurrent-neural-network-model)
`So limitation of the discussed architecture is that it learns from behind.`
I think it should be like this:
`So limitation of the discussed architecture is that it can not learn from behind.`
What is your opinion?

**Comment by mbadry1** [comment]
The second sentence is right:
`So limitation of the discussed architecture is that it can not learn from behind.`
I have updated it. 

Thanks,
